# Generated by Django 4.1.2 on 2022-10-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untirta', '0003_alter_dosen_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staf',
            name='nip',
            field=models.IntegerField(),
        ),
    ]
